name: gcloud
description: Setup Google Cloud SDK on Gith Actions
runs:
  using: 'node12'
  main: 'dist/index.js'
inputs:
  service-account-key:
    description: The service account key to use, base64-encoded.
    required: true
  version:
    description: Google Cloud SDK to use. If left null, will use the latest one.
    required: false
  components:
    description: Install additional components (e.g. beta, gsutils, etc.)
    required: false
  configure-docker:
    description: Configure Docker to interact with Google Cloud Container Registry.
    required: false
    default: false
