name: Tests
on: push
jobs:
  test:
    strategy:
      matrix:
        #os: [ubuntu-latest, macos-latest]
        #version: [latest, 245.0.0]
        os: [ubuntu-latest]
        version: [latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js 12
        uses: actions/setup-node@v1.2.0
        with:
          node-version: 12.x
      - name: Install Google Cloud SDK
        run: node dist/index.js
        env:
          INPUT_VERSION: ${{ matrix.version }}
          INPUT_PROJECT: auto
          # INPUT_PROJECT: ${{ secrets.GCLOUD_PROJECT }}
          INPUT_COMPONENTS: beta
          INPUT_SERVICE-ACCOUNT-KEY: ${{ secrets.GCLOUD_AUTH }}
      - name: Test Google Cloud SDK CLI
        run: |
          gcloud version
          gcloud config list account --format "value(core.account)"
