name: Tests
on:
  push:
    branches: ['**']
jobs:
  lint:
    name: Lint with ESLint / Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Run ESLint
        run: |
          npm install
          npm run lint
  test:
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04, macos-10.15, windows-2019]
        version: [latest, local, 245.0.0]
        project: [auto, matrix-education]
        exclude:
          - os: macos-10.15
            version: local
          - os: windows-2019
            version: local
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Google Cloud SDK
        uses: ./
        with:
          version: ${{ matrix.version }}
          project: ${{ matrix.project }}
          components: beta
          service-account-key: ${{ secrets.GCLOUD_AUTH }}
      - name: Test Google Cloud SDK CLI
        run: |
          gcloud version
          gcloud config list account --format "value(core.account)"
